app/src/main/java/com/metrolist/music/MainActivity.kt

Issue: https://github.com/mostafaalagamy/Metrolist/issues/197
Inside onClick i add an if statement where i made 2 checks for explore tab. 
The first check is responsible for double click the explore icon( if the user double click explore icon, open the search screen, and setting the flag for opening the explore screen to false in order not to open explore screen).
The else block is responsible for single tap the explore icon. if the user does not make a double click(thats why i have a coroutine scope with a delay in order to wait if the user make double click) the app navigates to explore screen without opening the search screen

Feature: Search by double click on Discover

---

app/src/main/res/drawable/shortcut_explore.xml
app/src/main/res/drawable/shortcut_library.xml
app/src/main/res/drawable/shortcut_search.xml

Issue: https://github.com/mostafaalagamy/Metrolist/issues/325
Fix: Change the color of the icons to black

Icons invisible in App Shortcuts

---

app/src/main/java/com/metrolist/music/ui/component/Lyrics.kt

**This PR enhances the way lyrics auto-scroll to make it feel more intuitive and similar to Spotify.**
What Changed?
- **Smarter syncing behavior:** Instead of blindly jumping to the current line after 4 seconds of inactivity, auto-scroll now only re-engages when the lyrics are positioned within a specific sync zone between 1/2 and 7/8 of the screen.
- If the user scrolls away and the line isn't in the sync zone anymore, it won’t automatically pull them back.
- If the user scrolls to the lyrics but they appear in the top half, it will wait until the lyrics reach the middle before following along.
- If the lyrics are at the bottom, they will move back to the middle after a short delay.
- **Immediate Sync on New Line:** When the lyrics are synced to a new line (i.e. the current line is …

Improve Lyric Auto-Scrolling Behavior

---

app/src/main/AndroidManifest.xml

This pull request adds the MediaButtonReceiver declaration in the AndroidManifest.xml to allow the app to respond to external media button events (e.g., Bluetooth headsets, Tasker, car controls, etc.).
This does not modify any other part of the app's logic, just enables compatibility with system-level playback controls.
Tested and working with Bluetooth headset and Tasker.

Add MediaButtonReceiver to support external media control

---

.github/workflows/build.yml
.github/workflows/build_pr.yml
.github/workflows/release.yml
app/build.gradle.kts

- Used debug.keystore for pull_request workflows
- Used persistent-debug.keystore for normal builds
- Added GITHUB_EVENT_NAME to workflow environments
- Unified APK build and signing behavior across workflows

fix: refactor Gradle signing to support dynamic keystore selection

---

app/src/main/kotlin/com/metrolist/music/ui/player/Player.kt

Fixes part of the issue #584 
Adds long press to copy for artist names & song title while keeping rest of the functionality of the app as it is.
I would like to use this PR to discuss the approach towards implementing the same for lyrics.
I have a couple of questions:
- Should there be an ability to select start & end of the text to copy or should the app just copy the line which was long pressed?
- Lyrics are not static & might automatically scroll down during the duration of long press. How should the app handle such scenarios?

feat: Long press to copy for Title & Artist in the player screen.

---

app/src/main/kotlin/com/metrolist/music/utils/YTPlayerUtils.kt
innertube/src/main/kotlin/com/metrolist/innertube/models/YouTubeClient.kt

No more "Unknown error" using Android Client.
There may still be cases where you see an "`Unknown error`", such as "`Please log in to confirm your age.`"
This is because we're not using this in that client:
```
loginSupported = true,
loginRequired = true
```
But we can't use it because NewPipeExtractor needs to be fixed (YoutubeSignatureUtils.java)

Fix Android client; Prioritize clients that usually work

---

app/src/main/kotlin/com/metrolist/music/ui/screens/HomeScreen.kt
innertube/src/main/kotlin/com/metrolist/innertube/pages/HomePage.kt

Enables the `Displays items, such as `Top music videos`, which are usually displayed only in grid items.
See https://github.com/OuterTune/OuterTune/pull/437 from which this code was adapted.

feat(UI/HomeScreen): display musicResponsiveListItemFlexColumnRenderer items in Home

---

app/src/main/kotlin/com/metrolist/music/ui/screens/HomeScreen.kt
app/src/main/kotlin/com/metrolist/music/viewmodels/HomeViewModel.kt
innertube/src/main/kotlin/com/metrolist/innertube/YouTube.kt

Uses the continuations to progressively load YT items, decreasing the overall loading time, as only a very small section of the total home screen needs to be loaded.
Port of https://github.com/OuterTune/OuterTune/pull/448
I'm also a bit confused, as to why, when loading the home page, all available section endpoints are loaded immediately, feels like something that should rather be done on demand?

perf: progressively load YT items

---

app/src/main/kotlin/com/metrolist/music/constants/PreferenceKeys.kt
app/src/main/kotlin/com/metrolist/music/ui/component/Lyrics.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/settings/AppearanceSettings.kt
app/src/main/res/values/metrolist_strings.xml

This commit introduces a new setting to allow users to choice the auto-scrolling behavior of lyrics.
- Adds `LyricsScrollKey` to `PreferenceKeys.kt`.
- Adds `lyrics_auto_scroll` string resource.
- Updates `Lyrics.kt` to respect the new `scrollLyrics` preference.
- Adds a `SwitchPreference` in `AppearanceSettings.kt` for toggling lyrics auto-scroll.

feat(lyrics): add option to switch auto-scroll option

---

app/src/main/kotlin/com/metrolist/music/ui/component/Lyrics.kt

Currently, turning off the "Auto Scroll Lyrics" setting doesn't fully disable lyric scrolling. It still scrolls to the current lyrics when they are on screen and stop only if the user manually scrolls away (the default behavior before the setting was implemented). When turned on, it would always scroll to the current lyrics. 
With this update, disabling the setting now completely stops all automatic lyric scrolling. When enabled, lyrics will scroll automatically only when the current line is visible, and will pause if the user scrolls manually.
I also fixed a little bug where it scrolled even when it shouldn't by adding a new check

Improve Auto Scroll Lyrics Setting

---

app/src/main/res/drawable/radio.xml

Change the size of the radio icon from `20dip` to `24dip` like the other icons. 
This makes the text aligned.
| Before | After |
| --------- | ------ |
| ![image](https://github.com/user-attachments/assets/0c760e70-ba92-489a-b6f8-6a8ea027a80c) | ![image](https://github.com/user-attachments/assets/abbf0c43-5afa-46e0-b6be-6ab0f50bdef7) |

Changing the size of radio icon to match the others

---

app/src/main/kotlin/com/metrolist/music/ui/component/SearchBar.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/search/OnlineSearchResult.kt

Better solution for #898 bug
I don't know why the SearchBar height value was set to 100.dp
The correct value should be 88.dp
**24.dp** - Android status bar height + **64.dp** - App Bar height

fix(layout): prevent ChipsRow overlap, better approach

---

innertube/src/main/kotlin/com/metrolist/innertube/pages/LibraryPage.kt
innertube/src/main/kotlin/com/metrolist/innertube/pages/RelatedPage.kt

Fixes #899 
Playlist in "Your YouTube playlists" section
> Removed playlist author from "Your YouTube playlists" section. 
Previously it showed `songCountText` twice.
**Now it only shows the number of songs in the playlist.**
Playlist in "RelatedPage"
> Similarly removed playlist author from `RelatedPage.kt`. 
**Now it only shows the number of views**
Album in "RelatedPage"
> Removed album author name because this information is not present in the Related section
> Added proper redirect to album author, which prevents app crashing
> **Now it only shows the album release date**

Refactors artist extraction for better reliability

---

app/src/main/kotlin/com/metrolist/music/ui/player/Queue.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/AlbumScreen.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/playlist/AutoPlaylistScreen.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/playlist/CachePlaylistScreen.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/playlist/LocalPlaylistScreen.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/playlist/OnlinePlaylistScreen.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/playlist/TopPlaylistScreen.kt

This commit refactors state management for song lists (e.g., using toMutableStateList and remember) to ensure proper UI updates. It also implements correct BackHandler behavior for search and selection modes, allowing users to exit these modes with the back button. Additionally, it fixes an issue where playing a song from a filtered list would use an incorrect start index for the playback queue

chore: Enhance UI state management and back navigation

---

app/src/main/kotlin/com/metrolist/music/lyrics/LyricsHelper.kt
app/src/main/kotlin/com/metrolist/music/ui/player/Queue.kt
innertube/src/main/kotlin/com/metrolist/innertube/InnerTube.kt
kugou/src/main/kotlin/com/metrolist/kugou/KuGou.kt
lrclib/src/main/kotlin/com/metrolist/lrclib/LrcLib.kt

Queue Button Crash Fix:
- Fixed app crashes when pressing lyrics button after backgrounding/resuming app
- Root cause: .alpha() modifier was causing composition instability during lifecycle changes
- Solution: Moved alpha logic from modifiers to tint/color properties
- Applied to both new and old player design layouts
- Now uses TextBackgroundColor.copy(alpha = ...) instead of .alpha() modifier
Lyrics Network Crash Fix:
- Fixed app crashes when fetching lyrics without network connection
- Root cause: Network requests made without checking connectivity status
- Solution: Added NetworkConnectivity checks before making network requests
- Added comprehensive error handling with try-catch blocks around network operations
- Added HTTP timeout configuration (15s request, 10s connect) to all …

Fix critical app crashes: Queue button and lyrics network issues

---

gradle.properties

- Increase HTTP timeout settings for JitPack downloads to 180 seconds
- Disable gradle caching to avoid SNAPSHOT dependency issues
This fixes the 'Read timed out' error when downloading timeago-parser:dev-SNAPSHOT from JitPack during release builds.

build: fix NewPipeExtractor timeout issues with JitPack

---

app/schemas/com.metrolist.music.db.InternalDatabase/22.json
app/src/main/kotlin/com/metrolist/music/db/DatabaseDao.kt
app/src/main/kotlin/com/metrolist/music/db/MusicDatabase.kt
app/src/main/kotlin/com/metrolist/music/db/entities/Playlist.kt
app/src/main/kotlin/com/metrolist/music/db/entities/PlaylistEntity.kt
app/src/main/kotlin/com/metrolist/music/ui/menu/YouTubePlaylistMenu.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/library/LibraryMixScreen.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/library/LibraryPlaylistsScreen.kt
app/src/main/kotlin/com/metrolist/music/utils/SyncUtils.kt

This feature allows playlists imported from YouTube Music to display their original thumbnails instead of generated ones from song covers.
Changes included:
- Add thumbnailUrl field to PlaylistEntity with database migration (v21 → v22)
- Update Playlist data class to prioritize YouTube Music thumbnails over song thumbnails
- Update DatabaseDao to save thumbnailUrl from YouTube Music API responses
- Update YouTubePlaylistMenu and SyncUtils to include thumbnail support
- Fix compilation errors in LibraryMixScreen and LibraryPlaylistsScreen
- Add new database schema file (22.json) for Room migrations
Implementation inspired by Muzza project's playlist thumbnail handling.
Technical details:
- Database version incremented from 21 to 22 with AutoMigration
- thumbnailUrl field added as nullable …

feat: Add YouTube Music playlist thumbnails support

---

app/src/main/kotlin/com/metrolist/music/constants/PreferenceKeys.kt
app/src/main/kotlin/com/metrolist/music/ui/player/Thumbnail.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/settings/PlayerSettings.kt
app/src/main/res/values/metrolist_strings.xml
app/src/main/res/values/strings.xml

Needed this myself because i find the static 5s limit to be low 
Adds a new option on player settings which when enabled, adds 5 seconds to each seek skip incrementally on each tap until the clicking stops found this myself when listening to long songs but it could be useful for other use-cases too

feat: Add ability for seek skip duration to be added up progressively

---

README.md
docs/F-DROID-SUBMISSION.md
docs/PUBLISH-TO-FDROID.md
gradle/libs.versions.toml
innertube/src/main/kotlin/com/metrolist/innertube/pages/NewPipe.kt
metadata/com.metrolist.music.yml

This change switches from NewPipe Extractor to PipePipe Extractor to resolve common playback issues including:
- Playback Error 403
- Source error 2004
- Playback stops after 30 seconds
Changes made:
- Updated gradle/libs.versions.toml to use PipePipeExtractor version 4240401 from InfinityLoop1308
- Updated NewPipe.kt to support new Response constructor with byte array parameter
- Added CancellableCall import and executeAsync method placeholder for compatibility
PipePipe Extractor is a fork of NewPipe Extractor that provides better deobfuscation support and resolves issues with broken WEB_REMIX and TVHTML5_SIMPLY_EMBEDDED_PLAYER clients that fallback to IOS client which gets blocked by YouTube.
References:
- Original PR: https://github.com/OuterTune/OuterTune/pull/730
- Original …

chore: use PipePipe Extractor to resolve playback issues

---

app/src/main/kotlin/com/metrolist/music/ui/screens/settings/AccountSettings.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/settings/SettingsScreen.kt
app/src/main/kotlin/com/metrolist/music/utils/Updater.kt

Use ABI-aware download URL for in-app updates. If `BuildConfig.ARCHITECTURE` is `universal`, open `Metrolist.apk`; otherwise open `app-{abi}-release.apk`.
- Add `Updater.getLatestDownloadUrl()` to construct the correct asset URL from `BuildConfig.ARCHITECTURE`.
- Replace hardcoded `Metrolist.apk` links in `SettingsScreen.kt` and `AccountSettings.kt` with the helper.
Users who installed a specific ABI (arm64/armeabi/x86/x86_64) should be directed to the matching APK instead of the universal one. This avoids unnecessary larger downloads and matches the installed flavor.
The CI publishes artifacts as:
- universal → `Metrolist.apk`
- arm64/armeabi/x86/x86_64 → `app-{abi}-release.apk`
These names match the URLs created by this change.
- Install any ABI flavor and navigate to Settings (or …

Use ABI-aware download URL for in-app updates

---

app/src/main/kotlin/com/metrolist/music/ui/player/Queue.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/HistoryScreen.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/artist/ArtistScreen.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/search/OnlineSearchResult.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/search/OnlineSearchScreen.kt
app/src/main/kotlin/com/metrolist/music/ui/utils/KeyUtils.kt

- Fixed composite key generation in OnlineSearchResult to prevent duplicates by adding index
- Fixed potential key conflicts in OnlineSearchScreen by adding prefixes for different item types
- Enhanced Queue implementation with index-based unique keys to prevent hashCode collisions
- Added index suffixes to ArtistScreen local songs and albums to ensure uniqueness
- Updated HistoryScreen key generation to include position index
- Created KeyUtils utility for future unique key generation needs
This resolves IllegalArgumentException errors related to duplicate keys in Jetpack Compose lazy lists.

Fix duplicate key issues in LazyColumn/LazyRow implementations

---

app/src/main/kotlin/com/metrolist/music/App.kt
app/src/main/kotlin/com/metrolist/music/constants/PreferenceKeys.kt
app/src/main/kotlin/com/metrolist/music/playback/DownloadUtil.kt
app/src/main/kotlin/com/metrolist/music/playback/MusicService.kt
app/src/main/kotlin/com/metrolist/music/ui/screens/settings/ContentSettings.kt
app/src/main/res/values/metrolist_strings.xml
app/src/main/res/values/strings.xml
innertube/src/main/kotlin/com/metrolist/innertube/InnerTube.kt
innertube/src/main/kotlin/com/metrolist/innertube/YouTube.kt
innertube/src/main/kotlin/com/metrolist/innertube/pages/NewPipe.kt

This pull request adds support for proxy authentication in the application, allowing users to configure proxy credentials (username and password) and use them for HTTP and SOCKS proxies throughout the app.
Tested on HTTP proxy with auth, and SOCKS5 proxy with auth
**Proxy Authentication Support**
* Added `ProxyUsernameKey` and `ProxyPasswordKey` preferences, and updated the app logic to handle proxy credentials when a proxy is enabled, including setting HTTP Basic authentication or a system authenticator depending on proxy type.
* Added a proxy configuration dialog in the settings screen, allowing users to input proxy type, URL, username, and password. Replaced the previous inline proxy settings with a single "Configure proxy" entry.
Closes: #618

feat: Add proxy auth support

---

app/src/main/kotlin/com/metrolist/music/ui/screens/playlist/LocalPlaylistScreen.kt

Adds the option to change the cover art for local (non-synced) playlists.
For local playlists, the note about the need to connect a phone number to YouTube Music is no longer displayed in the dialog; it is saved as a URI link to the file.
Changed the logic so that instead of saving to the previous `playlistThumbnail`, it now uses `overrideThumbnail`.
This PR also adds a default cover art for an empty local playlist.
If possible, please test this version

feat: Add custom thumbnail on local playlists

---

app/src/main/kotlin/com/metrolist/music/utils/YTPlayerUtils.kt
innertube/src/main/kotlin/com/metrolist/innertube/models/response/PlayerResponse.kt

This PR forces to select only the original audio tracks, thereby removing dubbed videos.
I believe this option should remain the default, as YouTube's auto-dubbing doesn't work well with music. 
If there are any other reasons why you would want to choose between different language versions, please let me know.
`isAutoDubbed` - `true` when format is with non-original language, `null` when is original
Closes #1550

feat: Force original audio language

---

app/src/main/kotlin/com/metrolist/music/ui/screens/playlist/LocalPlaylistScreen.kt

Brings back removed lock from other sorts than custom
Lock in other sorts blocks ability to remove song by swiping
Closes #1610

fix: Show lock in all sorts

---

app/src/main/kotlin/com/metrolist/music/playback/MusicService.kt

Steps to reproduce:
1. Remove all songs from queue
2. Click shuffle in bottom left
3. Crash
`java.lang.ArrayIndexOutOfBoundsException: length=0; index=0`

fix: Crash on shuffle empty queue
