innertube/src/main/java/com/metrolist/innertube/YouTube.kt, innertube/src/main/java/com/metrolist/innertube/models/GridRenderer.kt, innertube/src/main/java/com/metrolist/innertube/models/response/BrowseResponse.kt
Reverts mostafaalagamy/Metrolist#83
=> fix: revert "show all account playlists" commit 

app/src/main/java/com/metrolist/music/playback/MusicService.kt
Reverts mostafaalagamy/Metrolist#70
=> Revert "Better audio normalization"

app/src/main/java/com/metrolist/music/playback/DownloadUtil.kt, app/src/main/java/com/metrolist/music/playback/MusicService.kt, innertube/src/main/java/com/metrolist/innertube/InnerTube.kt, innertube/src/main/java/com/metrolist/innertube/models/response/PlayerResponse.kt, innertube/src/main/java/com/metrolist/innertube/utils/Utils.kt
This reverts commit 397968d8db07635dcffbb3beea85a97fd7c5aeb9.
=> Revert "fix: unable to download songs and video songs not playing"

app/src/main/java/com/metrolist/music/playback/DownloadUtil.kt, app/src/main/java/com/metrolist/music/playback/MusicService.kt, innertube/src/main/java/com/metrolist/innertube/YouTube.kt, innertube/src/main/java/com/metrolist/innertube/models/body/PlayerBody.kt, innertube/src/main/java/com/metrolist/innertube/models/response/PlayerResponse.kt, innertube/src/main/java/com/metrolist/innertube/utils/Utils.kt
This reverts commit ce82060cc647b8f2eb173355f0a66ba9a2090075.
=> Revert "fix: songs not playing - unknown error #113"

app/src/main/java/com/metrolist/music/playback/DownloadUtil.kt, app/src/main/java/com/metrolist/music/playback/MusicService.kt, innertube/src/main/java/com/metrolist/innertube/YouTube.kt, innertube/src/main/java/com/metrolist/innertube/models/body/PlayerBody.kt, innertube/src/main/java/com/metrolist/innertube/models/response/PlayerResponse.kt, innertube/src/main/java/com/metrolist/innertube/utils/Utils.kt
This reverts commit 7dd9838455b49c9ef35fa6c76807a5fa9ea9363e.
=> fix: songs not playing - unknown error

app/src/main/java/com/metrolist/music/playback/DownloadUtil.kt, app/src/main/java/com/metrolist/music/playback/MusicService.kt, innertube/src/main/java/com/metrolist/innertube/YouTube.kt, innertube/src/main/java/com/metrolist/innertube/models/body/PlayerBody.kt, innertube/src/main/java/com/metrolist/innertube/models/response/PlayerResponse.kt, innertube/src/main/java/com/metrolist/innertube/utils/Utils.kt
=> fix: songs not playing - added logged in bypass #113, close #142

app/src/main/java/com/metrolist/music/ui/screens/artist/ArtistItemsScreen.kt, innertube/src/main/java/com/metrolist/innertube/YouTube.kt, innertube/src/main/java/com/metrolist/innertube/models/GridRenderer.kt, innertube/src/main/java/com/metrolist/innertube/models/response/BrowseResponse.kt, innertube/src/main/java/com/metrolist/innertube/pages/ArtistItemsContinuationPage.kt, settings.gradle.kts
This reverts commit f043e6eb76e6bb286f3a0694e8c92fb042dc19a1.
=> Revert "fix: artist items continuation"

app/src/main/java/com/metrolist/music/db/MusicDatabase.kt, app/src/main/java/com/metrolist/music/ui/screens/HomeScreen.kt
This reverts commit c95b96711b4fbfec47b57e7fb7e0c0bfdd5aeab4.
=> Revert "fix: "downloaded playlist" in home page"

app/src/main/res/values-pt-rBR/strings.xml
Inglês:
I used it based on strings.xml in English, to be more up to date. Any errors found, leave a comment.
Portuguese Brasil:
Usei com base em strings.xml em inglês, para estar mais atualizado. Qualquer erro encontrado, deixe um comentário.
=> Update Portuguese Brasil strings.xml

app/schemas/com.metrolist.music.db.InternalDatabase/16.json, app/src/main/java/com/metrolist/music/constants/MediaSessionConstants.kt, app/src/main/java/com/metrolist/music/constants/PreferenceKeys.kt, app/src/main/java/com/metrolist/music/db/DatabaseDao.kt, app/src/main/java/com/metrolist/music/db/entities/SongEntity.kt, app/src/main/java/com/metrolist/music/playback/MediaLibrarySessionCallback.kt, app/src/main/java/com/metrolist/music/playback/MusicService.kt, app/src/main/java/com/metrolist/music/ui/component/Items.kt, app/src/main/java/com/metrolist/music/ui/menu/PlayerMenu.kt, app/src/main/java/com/metrolist/music/ui/menu/SelectionSongsMenu.kt, app/src/main/java/com/metrolist/music/ui/menu/SongMenu.kt, app/src/main/java/com/metrolist/music/ui/menu/YouTubeSongMenu.kt, app/src/main/java/com/metrolist/music/ui/screens/AlbumScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/HistoryScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/HomeScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/library/LibraryAlbumsScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/library/LibraryArtistsScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/library/LibrarySongsScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/playlist/AutoPlaylistScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/playlist/LocalPlaylistScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/playlist/TopPlaylistScreen.kt, app/src/main/java/com/metrolist/music/viewmodels/LibraryViewModels.kt
fix: liked songs random mixed and other > form Muzza "Maloy-Android"
=> fix (library): liked songs random mixed and other

app/src/main/res/values-el-rGR/strings.xml
=> Added Greek strings.xml

app/src/main/java/com/metrolist/music/ui/screens/LoginScreen.kt
- Should fix #302 (PR mostly made to address this)
- Improved cookie management for session persistence
- Improved auth handling
=> Fix for issue #302

app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml
style: Main language styled.
add: Main language exist keyword added.
=> upd: Turkish localization completed.

app/schemas/com.metrolist.music.db.InternalDatabase/17.json, app/src/main/java/com/metrolist/music/ui/screens/settings/AboutScreen.kt
Fix: Removed Music text from About page
=> Remove "Music" Text From About page

app/src/main/res/values-uk-rUA/strings.xml
The translation has been improved and completed (if I haven't missed anything) and is now up to date with the English version, I'll check it later. In addition, the order of the code was changed to match the English version (there were some inconsistencies which complicates translation).
=> Updated strings.xml (Ukrainian translation)

app/src/main/java/com/metrolist/music/ui/menu/PlayerMenu.kt, app/src/main/java/com/metrolist/music/ui/player/Player.kt, app/src/main/res/values/strings.xml
=> add copy link button to player UI and play Menu

kizzy/src/main/java/com/my/kizzy/remote/ApiService.kt, kizzy/src/main/java/com/my/kizzy/repository/KizzyRepository.kt
=> fix(Kizzy): fixes for Discord RPC

app/src/main/res/values-it/strings.xml, fastlane/metadata/android/it/full_description.txt, fastlane/metadata/android/it/short_description.txt
* Updated full_description.txt with some fixes
* Updated strings.xml with new keys and fixed old ones
* Added short_description.txt
=> Update Italian translation

app/src/main/java/com/metrolist/music/ui/screens/HomeScreen.kt, app/src/main/java/com/metrolist/music/viewmodels/HomeViewModel.kt, innertube/src/main/java/com/metrolist/innertube/models/MusicResponsiveListItemRenderer.kt, innertube/src/main/java/com/metrolist/innertube/pages/HomePage.kt
This reverts commit 8ab1e0f66e999c2a9984ddaf345b34ed54e85b17.
=> Revert "feat: new sections in home page, close #430"

app/src/main/java/com/metrolist/music/ui/component/Items.kt, app/src/main/java/com/metrolist/music/ui/screens/ChartsScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/ExploreScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/HomeScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/NavigationBuilder.kt, app/src/main/java/com/metrolist/music/viewmodels/ChartsViewModel.kt, app/src/main/res/values/strings.xml, innertube/src/main/java/com/metrolist/innertube/YouTube.kt, innertube/src/main/java/com/metrolist/innertube/models/YTItem.kt, innertube/src/main/java/com/metrolist/innertube/pages/ArtistItemsPage.kt, innertube/src/main/java/com/metrolist/innertube/pages/ChartsPage.kt, innertube/src/main/java/com/metrolist/innertube/pages/HistoryPage.kt, innertube/src/main/java/com/metrolist/innertube/pages/HomePage.kt
=> feat: support charts screen and added charts in explore screen

app/src/main/res/values-DE/strings.xml
=> update german translations

app/src/main/java/com/metrolist/music/playback/MusicService.kt, app/src/main/java/com/metrolist/music/ui/menu/SelectionSongsMenu.kt, app/src/main/java/com/metrolist/music/ui/menu/SongMenu.kt, app/src/main/java/com/metrolist/music/ui/menu/YouTubeSongMenu.kt, app/src/main/java/com/metrolist/music/utils/SyncUtils.kt
credit: OuterTune (Commit 19aed46)
=> fix(sync): actually like on remote when liking

app/src/main/java/com/metrolist/music/db/DatabaseDao.kt, app/src/main/java/com/metrolist/music/db/entities/Song.kt, app/src/main/java/com/metrolist/music/ui/screens/HomeScreen.kt, app/src/main/java/com/metrolist/music/viewmodels/CachePlaylistViewModel.kt
feat(home): add Cached playlist chip to home screen
=> feat(cache): display only fully cached songs

app/src/main/java/com/metrolist/music/MainActivity.kt, app/src/main/java/com/metrolist/music/ui/player/MiniPlayer.kt, app/src/main/java/com/metrolist/music/ui/player/Queue.kt, app/src/main/java/com/metrolist/music/ui/screens/search/LocalSearchScreen.kt, app/src/main/java/com/metrolist/music/ui/screens/search/OnlineSearchScreen.kt
- Apply pure black background for NavigationBar and TopAppBar when pureBlack is enabled
- Adjust TopSearch to use black background only when active and pureBlack is enabled
- Fix background behavior in OnlineSearchScreen for active SearchBar
- Add dynamic dividers above and below bottom headers when pureBlack is active
- Prevent black background from affecting ChipsRow filters when pureBlack is enabled
- Minor color adjustments: text colors adjusted for better readability on black background
- Improve consistency between collapsed and expanded states of TopSearch
=> feat: enhance pure black mode support across UI components

app/src/main/kotlin/com/metrolist/music/db/DatabaseDao.kt, app/src/main/kotlin/com/metrolist/music/ui/screens/NavigationBuilder.kt, app/src/main/kotlin/com/metrolist/music/ui/screens/artist/ArtistAlbumsScreen.kt, app/src/main/kotlin/com/metrolist/music/ui/screens/artist/ArtistScreen.kt, app/src/main/kotlin/com/metrolist/music/utils/SyncUtils.kt, app/src/main/kotlin/com/metrolist/music/viewmodels/AccountViewModel.kt, app/src/main/kotlin/com/metrolist/music/viewmodels/ArtistAlbumsViewModel.kt, app/src/main/kotlin/com/metrolist/music/viewmodels/ArtistViewModel.kt, innertube/src/main/kotlin/com/metrolist/innertube/models/MusicResponsiveListItemRenderer.kt, innertube/src/main/kotlin/com/metrolist/innertube/models/PlaylistPanelRenderer.kt
Based on OuterTune project: https://github.com/OuterTune/OuterTune
Co-authored-by: mattcarter11 <mattcarter11@users.noreply.github.com>
Co-authored-by: Michael Zh <mikooomich@users.noreply.github.com>
=> feat: add local screen for artists

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nn/strings.xml, app/src/main/res/values/metrolist_strings.xml, app/src/main/res/values/strings.xml
as per commit d901aac8394baf090d8fb0c85326df0d3af3aadf
=> translation: update upstream strings

app/src/main/kotlin/com/metrolist/music/constants/PreferenceKeys.kt, app/src/main/kotlin/com/metrolist/music/lyrics/LyricsUtils.kt, app/src/main/kotlin/com/metrolist/music/ui/component/Lyrics.kt, app/src/main/kotlin/com/metrolist/music/ui/screens/settings/AppearanceSettings.kt, app/src/main/res/values/metrolist_strings.xml
This PR introduces romanization for Korean lyrics.
Romanization based on https://github.com/fujaru/aromanize-js
Closes #848
=> feat: Added Korean romanization

app/src/main/kotlin/com/metrolist/music/MainActivity.kt
Fixes: #1088 #1106 #1076
PR adds handling of `list` parameter which is used to play the playlist.
=> fix: Handle `list` parameter in `/watch`

app/src/main/kotlin/com/metrolist/music/ui/player/Player.kt, app/src/main/kotlin/com/metrolist/music/ui/screens/playlist/OnlinePlaylistScreen.kt, app/src/main/kotlin/com/metrolist/music/ui/theme/PlayerColorExtractor.kt, app/src/main/kotlin/com/metrolist/music/ui/theme/PlayerSliderColors.kt, app/src/main/kotlin/com/metrolist/music/viewmodels/OnlinePlaylistViewModel.kt, app/src/main/res/values-ar/metrolist_strings.xml, app/src/main/res/values/metrolist_strings.xml, innertube/src/main/kotlin/com/metrolist/innertube/YouTube.kt, innertube/src/main/kotlin/com/metrolist/innertube/models/MusicPlaylistShelfRenderer.kt
Enhanced and refactor player and fix empty playlists don't load
=> fix: enhanced and refactor player with improved slider design and color extraction

app/src/main/kotlin/com/metrolist/music/ui/player/Queue.kt, app/src/main/kotlin/com/metrolist/music/ui/player/Thumbnail.kt
Reverts mostafaalagamy/Metrolist#1125
=> Revert "Analyze crash logs for root cause"

app/src/main/kotlin/com/metrolist/music/extensions/QueueExt.kt, app/src/main/kotlin/com/metrolist/music/models/PersistPlayerState.kt, app/src/main/kotlin/com/metrolist/music/models/PersistQueue.kt, app/src/main/kotlin/com/metrolist/music/playback/MusicService.kt
- Add support for saving different queue types (YouTubeQueue, YouTubeAlbumRadio, LocalAlbumRadio)
- Add PersistPlayerState model for saving player state
- Improve saveQueueToDisk function to save queue with its type
- Add more frequent state saving during playback
- Add state saving when player state changes
- Add player state restoration on app restart
=> Improve queue and player state persistence system

app/src/main/kotlin/com/metrolist/music/constants/PreferenceKeys.kt, app/src/main/kotlin/com/metrolist/music/extensions/PlayerExt.kt, app/src/main/kotlin/com/metrolist/music/playback/MusicService.kt, app/src/main/kotlin/com/metrolist/music/ui/screens/settings/PlayerSettings.kt, app/src/main/res/values/metrolist_strings.xml
Based on https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/408435
=> feat: add audio offload toggle

app/src/main/kotlin/com/metrolist/music/ui/component/Items.kt, app/src/main/kotlin/com/metrolist/music/ui/menu/YouTubePlaylistMenu.kt, app/src/main/kotlin/com/metrolist/music/ui/menu/YouTubeSongMenu.kt, app/src/main/kotlin/com/metrolist/music/viewmodels/AccountViewModel.kt
PR fixes the quality of some thumbnails from 120x120 to 544x544 which is common.
Closes #1078
=> fix: improving the quality of thumbnails

app/src/main/kotlin/com/metrolist/music/constants/PreferenceKeys.kt, app/src/main/kotlin/com/metrolist/music/lyrics/LyricsUtils.kt, app/src/main/kotlin/com/metrolist/music/ui/component/Lyrics.kt, app/src/main/kotlin/com/metrolist/music/ui/screens/settings/RomanizationSettings.kt, app/src/main/res/values/metrolist_strings.xml
Quick PR adding macedonian romanization requested in issue #1562. All done, ready for merge.
=> add macedonian romanization

app/src/main/kotlin/com/metrolist/music/utils/YTPlayerUtils.kt, innertube/src/main/kotlin/com/metrolist/innertube/models/Context.kt, innertube/src/main/kotlin/com/metrolist/innertube/models/YouTubeClient.kt
Ref: https://github.com/ReVanced/revanced-patches/blob/main/extensions/shared/library/src/main/java/app/revanced/extension/shared/spoof/ClientType.java
=> refactor(YouTubeClient): add new YouTube Clients
